# base
allow_reboot: false
manage_network: false

# Import my GPG key for git signature verification
root_gpgkeys:
  - name: kris@lamoureux.io
    id: FBF673CEEC030F8AECA814E73EDA9C3441EDA925

# proxy
proxy:
  servers:
    - domain: cloud.local.krislamo.org
      proxy_pass: http://127.0.0.1:8000

# docker
docker_official: true # docker's apt repos
docker_users:
  - vagrant

docker_compose_env_nolog: false # dev only setting
docker_compose_deploy:
  # Traefik
  - name: traefik
    url: https://github.com/krislamo/traefik
    version: d62bd06b37ecf0993962b0449a9d708373f9e381
    enabled: true
    accept_newhostkey: true # Consider verifying manually instead
    trusted_keys:
      - FBF673CEEC030F8AECA814E73EDA9C3441EDA925
    env:
      DASHBOARD: true
  # Nextcloud
  - name: nextcloud
    url: https://github.com/krislamo/nextcloud
    version: 0abc5cc6ba64ed94b7ddc6fd934f0fd62b8a6d11
    env:
      DATA: ./data

# traefik
traefik:
  ENABLE: true

# nextcloud
nextcloud:
  DOMAIN: cloud.local.krislamo.org
  DB_PASSWD: password
  ADMIN_PASSWD: password
