# base
allow_reboot: false
manage_network: false

# Import my GPG key for git signature verification
root_gpgkeys:
  - name: kris@lamoureux.io
    id: FBF673CEEC030F8AECA814E73EDA9C3441EDA925

# proxy
proxy:
  servers:
    - domain: cloud.local.krislamo.org
      proxy_pass: http://127.0.0.1:8000

# docker
docker_official: true # docker's apt repos
docker_users:
  - vagrant

docker_compose_env_nolog: false # dev only setting
docker_compose_deploy:
  # Traefik
  - name: traefik
    url: https://github.com/krislamo/traefik
    version: e03268af4cf942c47cba66c2112628dbcad1b756
    path: docker-compose.web.yml
    enabled: true
    accept_newhostkey: true
    trusted_keys:
      - FBF673CEEC030F8AECA814E73EDA9C3441EDA925
    env:
      ENABLE: true
  # Nextcloud
  - name: nextcloud
    url: https://git.krislamo.org/kris/nextcloud
    version: a2e38cec703839211e11dc8347b4cdd62fa6f24d
    env:
      DATA: ./data

# traefik
traefik:
  ENABLE: true

# nextcloud
nextcloud:
  DB_PASSWD: password
  ADMIN_PASSWD: password

# nextcloud
#nextcloud_version: stable
#nextcloud_admin: admin
#nextcloud_pass: password
#nextcloud_domain: cloud.local.krislamo.org

#nextcloud_dbversion: latest
#nextcloud_dbpass: password

# jenkins
jenkins_version: lts
jenkins_domain: jenkins.local.krislamo.org

# prometheus (includes grafana)
prom_version: latest
prom_domain: prom.local.krislamo.org
grafana_version: latest
grafana_domain: grafana.local.krislamo.org
prom_targets: "['10.0.2.15:9100']"

# nginx
nginx_domain: nginx.local.krislamo.org
nginx_name: staticsite
nginx_repo_url: https://git.krislamo.org/kris/example-website/
nginx_auth: admin:$apr1$T1l.BCFz$Jyg8msXYEAUi3LLH39I9d1 # admin:admin
nginx_version: latest
