# base
allow_reboot: false
manage_network: false

# docker
docker_user: vagrant

# traefik
traefik_dashboard: true
traefik_domain: traefik.vm.krislamo.org
traefik_auth: admin:$apr1$T1l.BCFz$Jyg8msXYEAUi3LLH39I9d1 # admin:admin

# nextcloud
nextcloud_version: stable
nextcloud_admin: admin
nextcloud_pass: password
nextcloud_domain: cloud.vm.krislamo.org

nextcloud_dbversion: latest
nextcloud_dbpass: password

# gitea
gitea_domain: git.vm.krislamo.org
gitea_version: 1
gitea_dbversion: latest
gitea_dbpass: password

# jenkins
jenkins_version: lts
jenkins_domain: jenkins.vm.krislamo.org

# prometheus (includes grafana)
prom_version: latest
prom_domain: prom.vm.krislamo.org
grafana_version: latest
grafana_domain: grafana.vm.krislamo.org
prom_targets: "['127.0.0.1', '127.0.0.1:9100']"
