# base
allow_reboot: false
manage_network: false

# docker
docker_users:
  - vagrant

# traefik
traefik_version: latest
traefik_dashboard: true
traefik_domain: traefik.vm.krislamo.org
traefik_auth: admin:$apr1$T1l.BCFz$Jyg8msXYEAUi3LLH39I9d1 # admin:admin
#traefik_acme_email: realemail@example.com # Let's Encrypt settings
#traefik_production: true

# nextcloud
nextcloud_version: stable
nextcloud_admin: admin
nextcloud_pass: password
nextcloud_domain: cloud.vm.krislamo.org

nextcloud_dbversion: latest
nextcloud_dbpass: password

# gitea
gitea_domain: git.vm.krislamo.org
gitea_version: 1
gitea_dbversion: latest
gitea_dbpass: password

# jenkins
jenkins_version: lts
jenkins_domain: jenkins.vm.krislamo.org

# prometheus (includes grafana)
prom_version: latest
prom_domain: prom.vm.krislamo.org
grafana_version: latest
grafana_domain: grafana.vm.krislamo.org
prom_targets: "['10.0.2.15:9100']"

# nginx
nginx_domain: nginx.vm.krislamo.org
nginx_name: staticsite
nginx_repo_url: https://git.krislamo.org/kris/example-website/
nginx_auth: admin:$apr1$T1l.BCFz$Jyg8msXYEAUi3LLH39I9d1 # admin:admin
nginx_version: latest

# wordpress
wordpress_version: latest
wordpress_domain: wordpress.vm.krislamo.org
wordpress_multisite: true
wordpress_dbversion: latest
wordpress_dbpass: password

# multisite (enable in admin panel then uncomment)
#wordpress_rule: "Host(`{{ wordpress_domain }}`) ||
#                 Host(`site1.{{ wordpress_domain }}`) ||
#                 Host(`site2.{{ wordpress_domain }}`)"
#
#wordpress_config_extra: |
#  define('MULTISITE', {{ wordpress_multisite | string }});
#  define('SUBDOMAIN_INSTALL', true);
#  define('DOMAIN_CURRENT_SITE', '{{ wordpress_domain }}');
#  define('PATH_CURRENT_SITE', '/');
#  define('SITE_ID_CURRENT_SITE', 1);
#  define('BLOG_ID_CURRENT_SITE', 1);
