# base
allow_reboot: false
manage_network: false

# Import my GPG key for git signature verification
root_gpgkeys:
  - name: kris@lamoureux.io
    id: FBF673CEEC030F8AECA814E73EDA9C3441EDA925

# docker
docker_users:
  - vagrant

docker_compose_env_nolog: false # dev only setting
docker_compose_deploy:
  # Traefik
  - name: traefik
    url: https://github.com/krislamo/traefik
    version: 31ee724feebc1d5f91cb17ffd6892c352537f194
    enabled: true
    accept_newhostkey: true # Consider verifying manually instead
    trusted_keys:
      - FBF673CEEC030F8AECA814E73EDA9C3441EDA925
    env:
      ENABLE: true
