# base
allow_reboot: false
manage_network: false

# minecraft
# Agree to EULA to start service in Vagrant
# i.e. sed -i 's/^#minecraft_eula/minecraft_eula/' ./dev/host_vars/minecraft.yml
#minecraft_eula: true

minecraft_onboot: vanilla
minecraft:
  - name: vanilla # 1.16.5 (https://mcversions.net/download/1.16.5)
    sha1: 1b557e7b033b583cd9f66746b7a9ab1ec1673ced
  - name: revelation # 3.4.0 (https://api.modpacks.ch/public/modpack/35/174)
    modpack: 35/174
    java: 8
