# base
allow_reboot: false
manage_network: false

# minecraft
# Agree to EULA to start service in Vagrant
# i.e. sed -i 's/^#minecraft_eula/minecraft_eula/' ./dev/host_vars/minecraft.yml
#minecraft_eula: true

minecraft_onboot: vanilla
minecraft_onboot_run: true
minecraft:
  - name: vanilla # 1.17.1 (https://mcversions.net/download/1.17.1)
    sha1: a16d67e5807f57fc4e550299cf20226194497dc2
    java:
      Xms: 1G
      Xmx: 1G
  - name: revelation # 3.4.0 (https://api.modpacks.ch/public/modpack/35/174)
    modpack: 35/174
    java:
      version: 8
      Xms: 4G
      Xmx: 4G
