# base
allow_reboot: false
manage_network: false

#mail:
#  host: smtp.gmail.com
#  from: automated@example.com
#  user: automated
#  password: password123
#  rootalias: personal@example.com

# rsnapshot
rsnapshot:
  - name: localhost
    intervals:
      - name: hourly
        count: 6
      - name: daily
        count: 4
    cron:
      - interval: hourly
        minute: "*/2" # every even minute
        #minute: 0
      - interval: daily
        minute: "1-59/2" # every odd minute
        #minute: 0
        #hour: 0
    #report:
    #  to: personal@example.com
    #  subject: Localhost Backup Report
    backups:
      - name: config
        source: /etc/
      - name: logs
        source: /var/log/
