# base
allow_reboot: false
manage_network: false

# docker
docker_users:
  - vagrant

# traefik
traefik_version: latest
traefik_dashboard: true
traefik_domain: traefik.vm.krislamo.org
traefik_auth: admin:$apr1$T1l.BCFz$Jyg8msXYEAUi3LLH39I9d1 # admin:admin
#traefik_acme_email: realemail@example.com # Let's Encrypt settings
#traefik_production: true

# nginx
nginx_domain: nginx.vm.krislamo.org
nginx_name: staticsite
nginx_repo_url: https://git.krislamo.org/kris/example-website/
nginx_auth: admin:$apr1$T1l.BCFz$Jyg8msXYEAUi3LLH39I9d1 # admin:admin
nginx_version: latest

# rsnapshot
rsnapshot:
  - name: webserver
    intervals:
      hourly: 6
      daily: 4
    cron:
      - interval: hourly
        minute: "*/2" # every even minute
        #minute: 0
      - interval: daily
        minute: "1-59/2" # every odd minute
        #minute: 0
        #hourly: 0
    backups:
      - name: staticsite
        source: "/opt/nginx/{{ nginx_name }}/"
      - name: logs
        source: /var/log/
