# base
allow_reboot: false
manage_network: false

# rsnapshot
rsnapshot:
  - name: localhost
    intervals:
      - name: hourly
        count: 6
      - name: daily
        count: 4
    cron:
      - interval: hourly
        minute: "*/2" # every even minute
        #minute: 0
      - interval: daily
        minute: "1-59/2" # every odd minute
        #minute: 0
        #hour: 0
    backups:
      - name: config
        source: /etc/
      - name: logs
        source: /var/log/
