# container settings
gitea_name: gitea
gitea_dbname: "{{ gitea_name }}-db"

# database settings
gitea_dbuser: "{{ gitea_dbname }}"

# host
gitea_root: "/opt/{{ gitea_name }}/data"
gitea_dbroot: "/opt/{{ gitea_name }}/database"
