# container settings
gitea_name: gitea
gitea_sshport: "127.0.0.1:222"
gitea_webport: "127.0.0.1:3000"
gitea_volume: "{{ gitea_name }}"
gitea_rooturl: "http://{{ gitea_domain }}"
gitea_signup: true

# database settings
gitea_dbtype: postgres
gitea_dbhost: host.docker.internal
gitea_dbname: "{{ gitea_name }}"
gitea_dbuser: "{{ gitea_name }}"

# host
gitea_root: "{{ docker_root }}/{{ gitea_name }}"
