- ansible.builtin.import_tasks: system.yml
  when: minecraft_eula

- ansible.builtin.import_tasks: java.yml
  when: minecraft_eula

- ansible.builtin.import_tasks: vanilla.yml
  when: minecraft_eula

- ansible.builtin.import_tasks: modpacks.yml
  when: minecraft_eula

- ansible.builtin.import_tasks: service.yml
  when: minecraft_eula
