- name: Deploy Minecraft systemd service
  template:
    src: minecraft.service.j2
    dest: "/etc/systemd/system/minecraft@.service"
  register: minecraft_systemd

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: true
  when: minecraft_systemd.changed

- name: Start Service
  service:
    name: "minecraft@{{ minecraft_onboot }}"
    state: started
    enabled: true
  when: minecraft_eula and minecraft_onboot is defined
