- name: Restart MariaDB
  ansible.builtin.service:
    name: mariadb
    state: restarted
  when: not mariadb_restarted
  listen: restart_mariadb

- name: Set MariaDB as restarted
  ansible.builtin.set_fact:
    mariadb_restarted: true
  when: not mariadb_restarted
  listen: restart_mariadb
