traefik_name: traefik
traefik_version: latest
traefik_options:
  - "--providers.docker"
  - "--providers.docker.exposedbydefault=false"
  - "--entrypoints.web.address=:80"
  - "--api=true"
traefik_ports:
  - "80:80"
