# Container settings
traefik_name: traefik
traefik_standalone: true
traefik_http_only: false
traefik_debug: false
traefik_web_entry: "80:80"
traefik_websecure_entry: "443:443"
traefik_localonly: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8"

# HTTPS settings
traefik_production: false
traefik_hsts_enable: false
traefik_hsts_preload: false
traefik_hsts_seconds: 0
traefik_http_redirect: true

# Host settings
traefik_root: "{{ docker_compose_root }}/{{ traefik_name }}"
