base_allow_reboot: true
base_manage_firewall: true
base_manage_network: false
base_network_type: static
base_locale_default: en_US.UTF-8

base_packages:
  - apache2-utils
  - bind9-dnsutils
  - btop
  - cryptsetup
  - curl
  - debsecan
  - hashdeep
  - htop
  - jq
  - kpartx
  - ncdu
  - pv
  - pwgen
  - rsync
  - screen
  - strace
  - tcpdump
  - tmux
  - trash-cli
  - tree
  - vim
  - wget

base_scripts: /srv/.scripts
base_ssh_ufw_rule: limit
base_swapfile_path: /swapfile
base_swap_sysctl_file: /etc/sysctl.d/70-swap.conf
