- name: Install MariaDB
  ansible.builtin.apt:
    name: mariadb-server
    state: present

- name: Change the bind-address to allow Docker
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regex: "^bind-address"
    line: "bind-address            = 0.0.0.0"
  register: mariadb_conf

- name: Restart MariaDB
  ansible.builtin.service:
    name: mariadb
    state: restarted
  when: mariadb_conf.changed

- name: Allow database connections
  community.general.ufw:
    rule: allow
    port: "3306"
    proto: tcp
    src: "{{ item }}"
  loop: "{{ mariadb_trust }}"
