- name: Install GnuPG
  apt:
    name: gnupg
    state: present

- name: Add AdoptOpenJDK's signing key
  apt_key:
    id: 8ED17AF5D7E675EB3EE3BCE98AC3B29174885C03
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

- name: Add MongoDB 3.6's signing key
  apt_key:
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    url: https://www.mongodb.org/static/pgp/server-3.6.asc

- name: Add UniFi's signing key
  apt_key:
    id: 4A228B2D358A5094178285BE06E85760C0A52C50
    keyserver: keyserver.ubuntu.com

- name: Install AdoptOpenJDK repository
  apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
    mode: 0644
    state: present

- name: Install MongoDB 3.6 repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/3.6 main
    mode: 0644
    state: present

- name: Install UniFi repository
  apt_repository:
    repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
    mode: 0644
    state: present

- name: Install MongoDB 3.6
  apt:
    name: mongodb-org
    state: present

- name: Install OpenJDK 8 LTS
  apt:
    name: adoptopenjdk-8-hotspot
    state: present

- name: Install UniFi
  apt:
    name: unifi
    state: present
