- name: Stop Bitwarden for rebuild
  ansible.builtin.service:
    name: "{{ bitwarden_name }}"
    state: stopped
  listen: rebuild_bitwarden

- name: Rebuild Bitwarden
  ansible.builtin.shell: "{{ bitwarden_root }}/bitwarden.sh rebuild"
  listen: rebuild_bitwarden

- name: Start Bitwarden after rebuild
  ansible.builtin.service:
    name: "{{ bitwarden_name }}"
    state: started
    enabled: true
  listen: rebuild_bitwarden
