- name: Stop Bitwarden for rebuild
  service:
    name: "{{ bitwarden_name }}"
    state: stopped
  listen: rebuild_bitwarden

- name: Rebuild Bitwarden
  shell: "{{ bitwarden_root }}/bitwarden.sh rebuild"
  listen: rebuild_bitwarden

- name: Start Bitwarden after rebuild
  service:
    name: "{{ bitwarden_name }}"
    state: started
    enabled: true
  listen: rebuild_bitwarden
