- name: Rebuild Bitwarden
  shell: "{{ bitwarden_root }}/bitwarden.sh rebuild"
  listen: rebuild_bitwarden

- name: Start Bitwarden
  shell: "{{ bitwarden_root }}/bitwarden.sh start"
  listen: start_bitwarden
