- name: Stop Bitwarden for rebuild
  ansible.builtin.service:
    name: "{{ bitwarden_name }}"
    state: stopped
  listen: rebuild_bitwarden

- name: Rebuild Bitwarden
  ansible.builtin.command: "{{ bitwarden_root }}/bitwarden.sh rebuild"
  listen: rebuild_bitwarden

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: true
  listen: rebuild_bitwarden

- name: Start Bitwarden after rebuild
  ansible.builtin.service:
    name: "{{ bitwarden_name }}"
    state: started
    enabled: true
  listen: rebuild_bitwarden

- name: Create Bitwarden's initial log file
  ansible.builtin.file:
    path: "{{ bitwarden_logs_identity }}/{{ bitwarden_logs_identity_date }}.txt"
    state: touch
    mode: "644"
  listen: touch_bitwarden
