- name: Reload Traefik container
  ansible.builtin.file:
    path: "{{ traefik_root }}/config/dynamic"
    state: touch
    mode: 0500
  listen: reload_traefik

- name: Restart Traefik
  ansible.builtin.service:
    name: "{{ docker_compose_service }}@{{ traefik_name }}"
    state: restarted
  listen: restart_traefik
