- name: Reload Traefik container
  file:
    path: "{{ traefik_root }}/config/dynamic"
    state: touch
  listen: reload_traefik

- name: Restart Traefik
  service:
    name: "{{ docker_compose_service }}@{{ traefik_name }}"
    state: restarted
  listen: restart_traefik
