- name: Install ddclient
  ansible.builtin.apt:
    name: ddclient
    state: present

- name: Install ddclient settings
  ansible.builtin.template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
    mode: "600"
  register: ddclient_settings

- name: Start ddclient and enable on boot
  ansible.builtin.service:
    name: ddclient
    state: started
    enabled: true
