- import_tasks: ansible.yml
  tags: ansible

- import_tasks: system.yml
  tags: system

- import_tasks: network.yml
  tags: network
  when: manage_network

- import_tasks: ddclient.yml
  tags: ddclient
  when: ddclient is defined

- import_tasks: wireguard.yml
  tags: wireguard
  when: wireguard is defined
