- import_tasks: ansible.yml
  tags: ansible

- import_tasks: system.yml
  tags: system

- import_tasks: network.yml
  tags: network
  when: manage_network

- import_tasks: duckdns.yml
  tags: duckdns
  when: duckdns is defined
