- name: Import Ansible tasks
  ansible.builtin.import_tasks: ansible.yml
  tags: ansible

- name: Import System tasks
  ansible.builtin.import_tasks: system.yml
  tags: system

- name: Import Firewall tasks
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall

- name: Import Network tasks
  ansible.builtin.import_tasks: network.yml
  tags: network
  when: manage_network

- name: Import Mail tasks
  ansible.builtin.import_tasks: mail.yml
  tags: mail
  when: mail is defined

- name: Import ddclient tasks
  ansible.builtin.import_tasks: ddclient.yml
  tags: ddclient
  when: ddclient is defined

- name: Import WireGuard tasks
  ansible.builtin.import_tasks: wireguard.yml
  tags: wireguard
  when: wireguard is defined

- name: Import Samba tasks
  ansible.builtin.import_tasks: samba.yml
  tags: samba
  when: samba is defined
