- name: Install network interfaces file
  ansible.builtin.copy:
    src: network-interfaces.cfg
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Install network interfaces
  ansible.builtin.template:
    src: "interface.j2"
    dest: "/etc/network/interfaces.d/{{ item.name }}"
    mode: "400"
  loop: "{{ interfaces }}"
  notify: reboot_host
