- name: Install network interfaces file
  copy:
    src: network-interfaces.cfg
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Install network interfaces
  template:
    src: "interface.j2"
    dest: "/etc/network/interfaces.d/{{ item.name }}"
  loop: "{{ interfaces }}"
  notify: reboot_host

- name: Install bridge utilities
  apt:
    name: bridge-utils
    state: present
