- name: Install Dockerbox Server
  hosts: "{{ PLAYBOOK_HOST | default('none') }}"
  become: true
  roles:
    - base
    - docker
    - traefik
    - nextcloud
    - jenkins
    - prometheus
    - nginx
