- name: Install Dockerbox Server
  hosts: "{{ PLAYBOOK_HOST | default('none') }}"
  become: true
  roles:
    - base
    - jenkins
    - docker
    - mariadb
    - traefik
    - nextcloud
    - proxy
