- name: Reload systemd manager configuration for all podman users
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ item }}"
  loop: "{{ podman_compose.keys() | list }}"
  listen: podman_compose_systemd

- name: Restart docker compose (podman) services
  ansible.builtin.systemd:
    state: restarted
    name: "compose@{{ item.service }}"
    scope: user
  become: true
  become_user: "{{ item.user }}"
  loop: "{{ podman_compose_restart_list | default([]) | unique }}"
  when: podman_compose_restart_list is defined
  listen: podman_compose_restart
