name: homelab-ci

on:
  push:
    branches:
      - main
      - testing

jobs:
  homelab-ci:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Install Tools
        run: brew install nmap tree

      - name: Install VirtualBox
        run: brew install --cask virtualbox

      - name: Install Vagrant
        run: brew install --cask vagrant

      - name: Install Ansible
        run: brew install ansible

      - name: Software Versions
        run: |
          printf "VirtualBox "; vboxmanage --version
          vagrant --version
          ansible --version

      - name: Vagrant Up with Dockerbox Playbook
        run: ./scripts/github-vagrant.sh
